#!/bin/bash

msgTag="Battery"
battery=$(acpi | awk '{print substr($4,0,3)" "$5" "$6" "$7}')
IFS=' ' read -ra bat <<< "$battery"
dunstify -a "check_battery" -u low -h string:x-dunst-stack-tag:$msgTag -h int:value:"${bat[0]}" "Battery"
