#!/bin/sh

case $BLOCK_BUTTON in
    2) alsamixer -D pulse sset Master toggle ;;
    4) alsamixer -D pulse sset Master 1%+ ;;
    5) alsamixer -D pulse sset Master 1%- ;;
esac

echo "$(amixer -c 0 get Master | awk 'FNR==5 {print substr($6,5,length($6)-2), $4}')"